# Generated by Django 4.2.5 on 2023-09-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500, null=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.balancemodel')),
            ],
            options={
                'db_table': 'api_rest_outgomodel',
            },
        ),
        migrations.CreateModel(
            name='IncomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500, null=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.balancemodel')),
            ],
            options={
                'db_table': 'api_rest_incomemodel',
            },
        ),
    ]
